### ISSUE TITLE
feedback on generated vm

### ISSUE THREAD

**Issue by karmab** [kubevirt/cloud-image-builder#93]
- misses virtctl in path
- misses cdi
- misses kubevirt ui
- for multus, might be helpful to create some network attachment definitions

**Comment by tripledes** [comment]
@karmab do we need this issue still open ?

**Comment by ptrnull** [comment]
/remove-lifecycle rotten
created jira to work on it

**Comment by codificat** [comment]
this was reviewed and it seems obsolte by now, only the CDI changes remaining which are now tracked in kubevirt.github.io/303.

/close
